patroni_superuser_password: ENC[AES256_GCM,data:FPZkSLKpE+D357Ctk82h97NIT55Tc4LTkA4n3zq0JhBj/zCgCrx+5w==,iv:SMDf08EO3sJYuXftMuOrYqpvwxV98uS6ebFxrNLrk5E=,tag:gVirxEjQx1bB5S1S0CVKww==,type:str]
patroni_replication_password: ENC[AES256_GCM,data:x4Lw5a8EOP29AZyqfY6gonl4+x6NC+6q3xBb6dzL/QE6yQjp0RtnLA==,iv:8K88FTwtH+MPPYo9f3QlHCLGdB5yeH8QuULRExXH998=,tag:yGNaRBeNkmBOcYTn8pQSYg==,type:str]
patroni_rewind_password: ENC[AES256_GCM,data:iHBc1aB3dbfAlKKBvnZOWAlG5mZrD99hAg0Pnwz8+CSU790xR+pXQA==,iv:bnAGQiT4EV+ZOHnEbXN1+v824ldCRTD9OIGo2DeqBHU=,tag:ZkebSKW78yHdv1LI1t2nPg==,type:str]
sops:
    lastmodified: "2026-02-16T14:49:16Z"
    mac: ENC[AES256_GCM,data:iKHdfea8UZMbIjXzC+Kw+704NCb5evhr4GL8CmZNBIJ356DYmLSYUYLxNQulbKI6geaTWGNC6Lo/xbcUZ4iF/pWIQipMfjxWS12cmnLVybRHPJv72vZJfleiKn7kg+9iObWLIr0nvoBwQcaAOhlXnS/AH3dlwg3hcW+MpN83fiA=,iv:oIKh5C5E+I8ZpRabxHlfCmcOCQ7awa4pUFB2tm2/aCc=,tag:MKM7Xp2KZ4VwT7QUb07tfA==,type:str]
    pgp:
        - created_at: "2026-02-16T14:49:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeebQOtJNR30SAQdAEUoRT1iEz9T8D5faqccIQArqVrnb592VXso5weXxuGcw
            SY+4J4xCqqtgFhb7cuAI/WjRTirodyXNrv7DyvPAskAkejwhflLF4YzYX9i2ny+G
            0l4B3X+6qYc2tomZCrp107ZEo6cgk1o7qWO630dpgvQ5NaAX8DdRBNQOnioX5YNH
            RpT8rTrwhCUnnAnlfZL/8WT9ltvMAZOS6I6yQ6LQ1ceVC1uD1zAx1RCgvwSg4STr
            =DxK2
            -----END PGP MESSAGE-----
          fp: E20595D143F7DC96
        - created_at: "2026-02-16T14:49:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGnE4EHLjsVoSAQdALr62tIWLTGeRVaZaxBUG/6ECRm5Uv7h+LVaABREJ0wcw
            xvdOvlBK4x2Wn7euK2rpsB+9V2C/vcPG37hbzbzHP8iJ+hRXWG/c6N4xs/QzEr4t
            0l4BHKJH7uyMqN39y7RYhHsm5s7jLtaOM9s1HFmiGVDxj62vS9VdBjFssL3mFtcJ
            3ag6MAEz5aWsbVXWKppP/IwfY9n/PSSgZuTBXDQHSfa0mpkiqY0TD3n+0gSnpTJK
            =6Imp
            -----END PGP MESSAGE-----
          fp: 8E3032515785D8F2
    unencrypted_suffix: _unencrypted
    version: 3.11.0
