pdns_postgres_db: ENC[AES256_GCM,data:ks7xkQ==,iv:9VbsAo5BQo9lsF6VLPgMu7d/3hMZUUtDPMnDEqXY8b4=,tag:IF8rC936SbrX5YVLPJpCFg==,type:str]
pdns_postgres_user: ENC[AES256_GCM,data:bRUnrw==,iv:zsdIZKM1hQmhc9R2uF3hkKFbHiKQBek9ipp2aylxgPI=,tag:OTTnMB+GL8sNXD+XT6Dc1Q==,type:str]
pdns_postgres_pass: ENC[AES256_GCM,data:6NwKXVO+SyMwiuCtOwhho/AYpYIseADlsqzsV+SGr9a8mH5b8dX8Iw==,iv:3CalRoeDdHEJlG7XsYmaN7ngPZZIa6ofcisRChNVKzs=,tag:W/ZvzgGtW/VRWLqW5rWW0A==,type:str]
#ENC[AES256_GCM,data:+ST1+AT7Vr2Z3Nyg/JRfbds4YbimAEB3smpX9lS8fj/wlAA=,iv:t3S5kL36DoJj3T5ElFSc0sL2gCBtzjcCxPZ4XJiAC+Y=,tag:6u9mfKPXxXTkVTNt7HGYSA==,type:comment]
pdns_api_key: ENC[AES256_GCM,data:5TczQUfzKRMKppehh9Q8S2fgMwTvmyUdKd1W6bI899j2aFEqRcy67A==,iv:YI6yUmAXATG9k5K6eYXeAC/LUJdaNa+DB5+PYGuZai0=,tag:jtRjpHTT0Q37Qch0CTHRZQ==,type:str]
sops:
    lastmodified: "2026-02-16T14:49:19Z"
    mac: ENC[AES256_GCM,data:+RiezAC15SUzMjBDA5a7N5d2AML6uvYE6iXXYXG6GjJGut0poUihbNUGbzgTziIdIjpJaleA5Ixr/YeB4Mfv6eSZsP82lntt8PuBjza4lKYMNBFJF88xsRyTUqdbh/Q18Sa3MxoX7weAC3SeStFRL1QpGaFw5WyjG+wZ1S/II+8=,iv:BNmhWnEvH3D6Vzv+8GaoeLI1GV+FGKpxYg9O5wrZi1k=,tag:e7Nd0D2SnTxietCIKPk+ZA==,type:str]
    pgp:
        - created_at: "2026-02-16T14:49:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeebQOtJNR30SAQdAPA6npW6C056OynkvC2r/mZHYGHDO1v19fPrOGqWIilAw
            AetlumXQjo5aEXmQ8QTLcloTH8XFHPWrovaX4nBgkQnFMH840ydGCoWPNHZVfuYw
            0lwBq7+45SFzq8uT7VvENvZVV8ABolyyJ414aO/Tt/r/IEW7pNq6pjnhsbwbjVTu
            Hsv+PmRT/S4Os2KxC8XX7fw6Grt75yOf+FMhnPhfizy/3W17ZUh4iwXhQKs8dQ==
            =Gc3/
            -----END PGP MESSAGE-----
          fp: E20595D143F7DC96
        - created_at: "2026-02-16T14:49:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGnE4EHLjsVoSAQdApbVup3Hrq9XcAwuRNipXmdk6jPQVJ0e6/5IxgMOtTDMw
            hswXgSyibHVJfrYUUhZqBMUfmEdgc/vqlcR68apEtS4brKscE1fYJ6kwYe4Azp0a
            0lwB5HNXQzA9Jqq2jNxATMduaBpgeq4lNoCjaP2ksETq2T45HOuTtUa1cxaYVEzY
            +QQBHQ23K+d/L53+nu7oXaQoBBBEUa4bP1F+jSi3HCtqNhKf4QWzuWkAcUrsQw==
            =p6F+
            -----END PGP MESSAGE-----
          fp: 8E3032515785D8F2
    unencrypted_suffix: _unencrypted
    version: 3.11.0
