all:
  vars:
    ansible_user: root

  hosts:
    localhost:
      ansible_connection: local

    pve01.inf.nevi.network:

    net01.inf.nevi.network:
      ip: 10.64.20.4
      ip6: fdbc:ba6a:38de:20::4
    net02.inf.nevi.network:
      ip: 10.64.20.5
      ip6: fdbc:ba6a:38de:20::5
    net03.inf.nevi.network:
      ip: 10.64.20.6
      ip6: fdbc:ba6a:38de:20::6

    relay01.home.nevi.network:
    relay02.home.nevi.network:

    tpeap.mgmt.nevi.network:

vyos:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    ansible_user: vyos
  hosts:
    rtr01.rtr.nevi.network:
      vyos_config: ../vyos/diff/rtr01.txt
    rtr02.rtr.nevi.network:
      vyos_config: ../vyos/diff/rtr02.txt

etcd_ca:
  hosts:
    localhost:
patroni_ca:
  hosts:
    localhost:
caddy_ca:
  hosts:
    localhost:

kubelet:
  children:
    etcd:
      hosts:
        net01.inf.nevi.network:
        net02.inf.nevi.network:
        net03.inf.nevi.network:

    patroni:
      hosts:
        net01.inf.nevi.network:
        net02.inf.nevi.network:

    patroni_haproxy:
      children:
        kea:
          hosts:
            net01.inf.nevi.network:
            net02.inf.nevi.network:
        pdns:
          hosts:
            net01.inf.nevi.network:
            net02.inf.nevi.network:

    chrony:
      hosts:
        net01.inf.nevi.network:
        net02.inf.nevi.network:

    dhcrelay:
      vars:
        dhcrelay_up: eth20
        dhcrelay_down:
          - eth1
          - eth10
          - eth11
          - eth30
      hosts:
        relay01.home.nevi.network:
          dhcrelay_v4: 10.64.20.4
          dhcrelay_v6: fdbc:ba6a:38de:20::4
        relay02.home.nevi.network:
          dhcrelay_v4: 10.64.20.5
          dhcrelay_v6: fdbc:ba6a:38de:20::5

    caddy:
      hosts:
        net01.inf.nevi.network:
        net02.inf.nevi.network:

    tpeap:
      hosts:
        tpeap.mgmt.nevi.network:
